---
- name: Download Terraform binary
  get_url:
    url: "{{ tf_download_url }}"
    dest: /tmp

- name: Extract Terraform binary to temp file
  unarchive:
    src: "/tmp/{{ tf_archive_name }}"
    dest: /tmp

- name: Delete Terraform archvie
  file:
    path: "/tmp/{{ tf_archive_name }}"
    state: absent

- name: Move Terraform binary
  copy:
    src: /tmp/terraform
    dest: "/usr/local/bin/terraform{{ tf_install_version }}"
    mode: "0774"

- name: Delete Terraform binary temp file
  file:
    path: /tmp/terraform
    state: absent

- name: Create symlink for default Terraform binary version
  file:
    src: "/usr/local/bin/terraform{{ tf_default_version }}"
    dest: "/usr/local/bin/terraform"
    mode: "0774"
    state: link